### PR TITLE
[ButtonSetup] Add Long press Tv and Radio buttons and the option to r…

### PR DESCRIPTION
**Pull request by Ev0-BH**
…un a script from /usr/script

(cherry picked from commit 82e52c77a98c7af77ca52166ae732123e29e3552)

### CODE REVIEW

**Comment by TwolDE2** [comment]
Surely you can run scripts from ViX plugin, so why would you do this hack????

**Comment by Huevos** [comment]
> 
> 
> Surely you can run scripts from ViX plugin, so why would you do this hack????

Yes you can. No idea why this would be needed.

**Comment by Ev0-BH** [comment]
So you can set a script to run from a single button press.

**Comment by TwolDE2** [comment]
But you can do that already from the ViX plugin - this doesn‘t add any value other than code for a personal wish

**Comment by Ev0-BH** [comment]
Well OBH doesn't have the vix plugin, which is why I added it.

If you don't want / need the code, feel free to close the request, it's not a problem :)

**Pull request closed without merging**
