### PR TITLE
Provide option to hide done timers

### PR DESCRIPTION
**Pull request by SimonCapewell**
Updates to timer edit list:
- Add another option to hide finished timers
- Add ch+ and ch- to move to top and bottom of timer list, similar to movie list
- Removal of commented out debug print lines

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Where is the option to hide timers meant to be configured?

Just for info, old timers were usually kept to avoid duplicate recordings.

**Comment by SimonCapewell** [comment]
It's the 12th item on _User Interface | Settings_. _Position of finished timers_ 

Yes, it's fine to keep the timers to avoid duplicates, just not very useful to have them clogging up the list!

**Comment by SimonCapewell** [comment]
You're partly right. I should've included UsageConfig.py

**Comment by Huevos** [comment]
Is this ready to merge?

**Comment by AbuBaniaz** [comment]
Done.

**Pull request merged**
