### PR TITLE
Additional pixmap blit alignment options

### PR DESCRIPTION
**Pull request by SimonCapewell**
Text has options to align right or align centrally within the bounding rectangle. Pixmap should have this as well so that pixmaps that are smaller than the bounding rectangle or those that don't match the aspect ratio can be easily aligned if required.

This PR adds 4 new flags `BT_HALIGN_CENTER`, `BT_HALIGN_RIGHT`, `BT_VALIGN_CENTER` and `BT_VALIGN_BOTTOM`.
The existing alignment for scaled, keep aspect ratio pixmaps looks to have meant to be centered, but actually biases to the top of the bounding rect, so has been replaced.

MovieList now accepts `center` for the skin parameters `pbarShift`, `partIconeShift`, `trashShift`, and `dirShift`, which means progressbars and 3 types of icons align automatically with text regardless of how many rows are shown in the movielist.

### CODE REVIEW

**Comment by Huevos** [comment]
Simon you are doing something wrong. You shouldn't have all these merge commits.

**Comment by SimonCapewell** [comment]
Can we have some guidance on best practice for keeping a forked e2 repo up to date and how to contribute without these merges making things look untidy?

**Comment by SimonCapewell** [comment]
Hang on. There's an alignment problem with movielist progress/playback icons. Fix coming...

How do you want it submitted? Another PR on the same branch, or a new branch?

**Comment by AbuBaniaz** [comment]
We have a thread on the forum.

**Comment by AbuBaniaz** [comment]
As merged, will have to be new request

**Comment by Huevos** [comment]
Fork OpenViX/enigma2
Now you have SimonCapewell/enigma2
Clone that to your local.
Set up OpenViX/enigma2 as a remote on your local clone.
Never make any changes to the "Dev" branch.
To update SimonCapewell/enigma2/Dev pull from OpenViX/enigma2/Dev
Always pull-rebase, not pull-merge, otherwise it will show the merge commits.

When you want to do a PR create a new branch from the last commit in Dev. Add your changes to this new branch and then push to your remote. Do a PR.

**Comment by SimonCapewell** [comment]
This this is what's wrong:
*Always pull-rebase, not pull-merge, otherwise it will show the merge commits.*
Will a pull-rebase next time around get rid of the mess of historic? If not, I'll just re-fork to get a clean repo

**Comment by Huevos** [comment]
I would refork so you are starting from clean.

You pull-merge if you want the merge commits to show in the history, but doing so means they show in your PRs too because they don't exist on the repos you forked from.

As long as you pull-rebase and you never commit to your dev branch, that branch should always match OpenViX/enigma2/Dev.

**Pull request merged**
