### PR TITLE
Ensure the was_controlled_shutdown flag is cleared even when enigma2 …

### PR DESCRIPTION
**Pull request by original-birdman**
…dies from a signal.

### CODE REVIEW

**Comment by Huevos** [comment]
You don't seem to be working on the latest version.

Please pull and try again.

**Comment by original-birdman** [comment]
I did a pull 5 mins before adding the fix.

As I switched back to the Developer branch after pushing my fix I get:
```
[parent]: git checkout Developer
Switched to branch 'Developer'
Your branch is up-to-date with 'upstream/Developer'.
```
So what am I behind?

**Comment by Huevos** [comment]
You are doing the same thing that has already been done 25 lines above.

https://github.com/OpenViX/enigma2/blob/bbc770ee5939934a9a2821dab1137b915220985e/tools/enigma2.sh.in#L326-L351

**Comment by original-birdman** [comment]
Ah, I see what you mean.
Although that other addition is in the wrong place, as it precedes the wait ${enigma2pid}, which is where the script waits after enigma2 starts. So that code wipes out the value as soon as enigma2 starts up.
And the sed command is simpler.

The "# Enable generation of core dumps with ELF header included." section is where it is for a reason.

So revert that one and add mine.

**Comment by Huevos** [comment]
If I revert that your commit won't merge. So can you make a commit that removes that and replaces with yours please.

**Pull request merged**
