### PR TITLE
Fix clipping of right aligned service name

### PR DESCRIPTION
**Pull request by SimonCapewell**
When right aligning the service name in the graph EPG, the right edge of the text is clipped slightly short by a few pixels (varies a bit depending on skin). This is also the case if the service number is right aligned and the service name is not being shown.

This change fixes the problem by consistently applying padding around each item when calculating the size of the service rect as well as when building the items to draw.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
With existing file
epg pre simon

With file in pull request
epg post simon

**Comment by IanSav** [comment]
Can the change please be highlighted in the sample images.

**Comment by AbuBaniaz** [comment]
Already highlighted. Have a look at `BBC ONE London`

**Comment by IanSav** [comment]
Thanks for confirming.  My problem is that the "BBC ONE London" text in not right aligned so I didn't see how this correlated to the code change.

My feedback is that the "BBC ONE London" text right padding seems a little excessive.

**Comment by SimonCapewell** [comment]
I'd agree with that. I'll tweak things a little this evening

**Comment by SimonCapewell** [comment]
Actually, the column width turns out to be user defined, so the "right padding" in screenshot 2 is the specified width of the column. What do you think of the padding around the picon and between picon and servicename?

**Comment by SimonCapewell** [comment]
Added another performance improvement. Clocks array was loading the same pixmap repeatedly, which adds up to another 20-30ms load time

**Comment by Huevos** [comment]
Was that an accident adding that to this PR?

**Comment by SimonCapewell** [comment]
Not really. I was nosing around the EPG list and discovered some rather repetetive code. Didn't fancy creating another branch and another PR - this is what's running on my box this evening

**Comment by Huevos** [comment]
Please can you not mix them because otherwise it is impossible to do a "squash and merge" because it means 2 non-related items end up in one commit.

**Comment by SimonCapewell** [comment]
No problem. Another PR incoming

**Comment by Huevos** [comment]
Thanks. If you have a fix to the right hand padding width it can be added here before merging this one.

**Comment by SimonCapewell** [comment]
I don't believe a fix is needed unless the new spacing around the picon is undesirable. The right hand padding as shown in the 2nd screenshot is the width set in Abu's options. I can replicate by setting the servicename width to 200, but if I reduce it to 180, the names are clipped. This is the same sort of behaviour that the previous code had.

**Comment by Huevos** [comment]
Blame Ian, it was him that said it was excessive. ;)

**Comment by AbuBaniaz** [comment]
BTW, I've not altered any options. This is how it looks on vix night hd. Different picon set is being used.

epg post simon_vnhd

**Comment by IanSav** [comment]
> Actually, the column width turns out to be user defined, so the "right padding" in screenshot 2 is the specified width of the column. What do you think of the padding around the picon and between picon and servicename?

That spacing is fine.

(Now you can see why I wanted a pointer at exactly what spacing I was reviewing.  :) )

**Comment by RobvanderDoes** [comment]
Actually I think the spacing around the service number is too wide.

**Comment by SimonCapewell** [comment]
OK, room for some more tweakage. You'll see that the default is `serviceNumberPadding = 9` compared to `serviceNamePadding = 3`, perhaps that 9 needs to be a bit smaller

**Comment by RobvanderDoes** [comment]
Thanks for the tip: I tried `serviceNumberPadding = 3` and that seems fine to me.
But others may find otherwise, depending on skin/font size/number of entries.

**Pull request merged**
