### PR TITLE
update es.po

### PR DESCRIPTION
**Pull request by norhap**
guys, my translations es.po.
[es.zip](https://github.com/OpenViX/enigma2/files/4167201/es.zip)

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Your pull request has conflicts.

**Comment by AbuBaniaz** [comment]
We can't accept this pull request you are changing python files to effect a translations. That breaks all other translations Please create a new branch on your fork,  commit the language changes to it. Then submit from the new branch to our Dev branch.

There are a few files where strings are not translatable,  they will need tweaking.

**Comment by AbuBaniaz** [comment]
Debug log must remain in English US.

Also, it seems you are copying in code from another image. Instead of removing our debug details , consider submitting pull request to them to to add the debug log. 

One way of doing things is:
Fork project
Create new branch in your fork.
Make changes in new branch of your fork
Create pull request
Once merged, delete your new branch.

**Comment by Huevos** [comment]
This has been cause because someone on PLi has hacked timer.py and added half the code from recordtimer.py into that file. Timer.py is now completely mangled on OpenPLi.

**Pull request closed without merging**
