### PR TITLE
Add support for KA-SAT (9°E) LNBs

### PR DESCRIPTION
**Pull request by wmoldwin**
This adds LOF settings for the official KA-SAT LNB (Inverto IDLW-TWNLRA20-D212O-OPP) used by the Irish Saorsat service.

### CODE REVIEW

**Comment by Huevos** [comment]
Thanks.

**Comment by conorg12** [comment]
Would it be possible to integrate the following SaorSat settings into AutobouquetsMaker as they are needed when using a Ka band universal LNB please. 

Saorsat parameters using a Ka-Sat Universal LNB (input freq 19.7-20.2 GHz, output freq 1500-1000 MHz)
KA-SAT @ 9E
10.765 GHz, Vertical Polarisation,
DVB-S2 QPSK,
SR 25000 with 2/3 FEC

Thanks a lot

**Comment by AbuBaniaz** [comment]
ABM works with the Ka-Band LNB. Please read the top of the provider file.

https://github.com/oe-alliance/AutoBouquetsMaker/blob/master/AutoBouquetsMaker/providers/sat_0090_saorsat.xml

**Comment by conorg12** [comment]
Thanks for the quick reply but the transponder settings that are built in to ABM are missing the required settings:

KA-SAT @ 9E
10.765 GHz, Vertical Polarisation,
DVB-S2 QPSK,
SR 25000 with 2/3 FEC

I know that the above are correct as they work when I do a user defined manual scan but when ABM does its own scan, it is unable to tune to SaorSat as its scan table is missing the correct transponder setting.

Can the transponder information be added to ABM.

Thanks

**Comment by Huevos** [comment]
Can you insert you suggested changes into Saorsat provider file and check it works?

**Comment by conorg12** [comment]
This is the missing transponder info
<transponder frequency="10765000" symbol_rate="25000000" polarization="1" fec_inner="2" system="1" modulation="1"/>

I'm sorry but I don't know how to integrate this into ABM

**Comment by AbuBaniaz** [comment]
We are advised ABM works with the settings in the file. Please start a thread on the forum with a debug log showing the issue

**Pull request merged**
