### PR TITLE
Fix long Ch+/Ch- failure to change PiP channel

### PR DESCRIPTION
**Pull request by SimonCapewell**
Also remove code for the channelbutton_mode option that was removed from the setup menu in 2014

### CODE REVIEW

**Comment by Huevos** [comment]
Was this not for merging?

**Comment by SimonCapewell** [comment]
Huh. Thought it'd been merged already :-/

**Comment by SimonCapewell** [comment]
Rebased this onto Dev, which should sort things out

**Comment by AbuBaniaz** [comment]
I've cherry picked these in. Thanks.

**Pull request closed without merging**
