### PR TITLE
Add back code lost in changes to Py3 and update the comment to reflec…

### PR DESCRIPTION
**Pull request by original-birdman**
…t these.

### CODE REVIEW

**Comment by Huevos** [comment]
You need to state the encoding.

**Comment by original-birdman** [comment]
> You need to state the encoding.

No you don't.  The documented default encoding is utf8, and that is what we are dealing with with Unicode string <-> byte string conversions.

**Comment by Huevos** [comment]
I know what the default encoding is, but if that changes your code will be broken.

**Comment by original-birdman** [comment]
If the default encoding changes then I would expect a large number of things to be broken.
This is why APIs are documented and not changed.

**Pull request closed without merging**
