### PR TITLE
Ensure updated sort method is saved in per-directory mode.

### PR DESCRIPTION
**Pull request by original-birdman**
In global sort mode let the user choose whether the change is permanent or temporary.

### CODE REVIEW

**Comment by original-birdman** [comment]
Redo of https://github.com/OpenViX/enigma2/pull/380 that really does allow for the fact that https://github.com/OpenViX/enigma2/commit/03ebf8a9b5b054ea763252e1dfe147a0aa1cf907 got in the way.

**Comment by original-birdman** [comment]
The further refinements are being discussed at:
https://www.world-of-satellite.com/showthread.php?60840-Issues-with-new-MovieSelection-changes&p=481559&viewfull=1#post481559
_et seq_

**Comment by RobvanderDoes** [comment]
I tested this extensively and I can't see any reason not to accept this.

**Comment by original-birdman** [comment]
Thanks. Now I can look at fixing the other issues.

**Pull request merged**
