### PR TITLE
Updated finnish translation

### PR DESCRIPTION
**Pull request by Orlandoxx**
One change to About.py.

### CODE REVIEW

**Comment by Orlandoxx** [comment]
Can someone merge this, please ?

**Comment by AbuBaniaz** [comment]
Done. Can you please also update the pot file for the benefit of other people.

**Comment by Orlandoxx** [comment]
Thanx. I would, but no idea about pot file. Can you give advice ?

**Comment by Huevos** [comment]
I'm not sure what Abu means. The latest po files are available on the receiver.

`opkg install enigma2-po`

**Comment by Orlandoxx** [comment]
Maybe he means updating enigma2.pot that other translators can find out what's new and what have changed ?

**Comment by AbuBaniaz** [comment]
https://github.com/OpenViX/enigma2/blob/Developer/po/enigma2.pot

**Comment by Orlandoxx** [comment]
Is it created by some script ?

**Comment by AbuBaniaz** [comment]
There are two scripts which don't work too well.  We have a thread on forum. For example they remove the translations for `1st Infobar timeout` 

I thought you had a way of doing thus.

**Comment by Huevos** [comment]
.pot file is discarded by the build.
https://github.com/OpenViX/enigma2/blob/Developer/po/Makefile.am#L32

**Comment by Orlandoxx** [comment]
I check when changes are done by searching _(" from that py-file and then search that from fi.po. If not found, I add it.

**Comment by Orlandoxx** [comment]
How did Huevos get this '[fi.po] latest version from buid for Orlandox to tweak' on Dec 29, 2022 ?? commit 9dc3371

**Pull request merged**
