### PR TITLE
Improve ui responsiveness

### PR DESCRIPTION
**Pull request by SimonCapewell**
The Grid EPG and Skin browser screens are slow to load on my ET8500. This PR addresses the perception of slow button response by showing these screens immediately with a "Please wait" message, in the same way as the Movie Selection screen.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Simon, we already have the message showing unless box is nextgen. Can you test with removing that condition only, without your additional coding changes? To rule out skin issues, please check with vix night hd

https://github.com/OpenViX/enigma2/blob/Dev/lib/python/Screens/EpgSelection.py#L99

https://github.com/OpenViX/enigma2/blob/acc0c5f0949ab4d6bc05674dd58e60b4be7f36ac/lib/python/Screens/EpgSelection.py#L380

**Comment by SimonCapewell** [comment]
Yes, I'd already had a look at how the non nextgen code works; however it's not obvious why you'd want  a deliberate 800ms delay between `EPGSelection.init` and `onCreate`, where the work that's currently taking the bulk of the time resides.

Here's some figures from ET8500 with VIX Night HD:

| step | VIX Night HD | Slyk Q |
| --- | --- | --- |
| key release, `init` | 80ms | 90ms |
| Skin load | 130ms | 300ms |
| LCD skin load | 80ms | 80ms |
| `onCreate` | 120ms | 160ms |

Which amounts to a palpable delay of 400ms between releasing the Guide button and the Graph EPG actually showing on screen which is sufficient to make it feel that the remote button press hasn't been seen. A threshold of 100ms is considered the point at which you start to feel that things are a bit sluggish, but as you can see, even getting within 200ms is challenging. The `not nextgen` code path delays the screen a further 800ms, making 1.2 seconds from button press to being ready for input. I'm sure there's a reason for it, but not having oldgen hardware, it's not possible to see the consequences of making this timer a "yield" timer of 1ms.

**Comment by AbuBaniaz** [comment]
My suggestion to use a dfferent skin was for the "lab1" item. If it is not in the skin, you won't see the notification.

**Comment by SimonCapewell** [comment]
Regardless of the presence of `lab1` you'll see UI much sooner though. In the current release build, nothing gets shown in response to the keypress until everything, background, graphics, timelines, grid content, current selection are constructed. This change tries to get an indication that the keypress has been received as soon as it can and then fills in the rest later.

**Comment by SimonCapewell** [comment]
BTW, I'd be intested to see some absolute timings for the graph EPG on other hardware.

**Comment by Huevos** [comment]
We either need to use the 800 delay on all hardware, or remove it and test this code.

I don't recall the movielist taking so long to load until recently. But I change to a 2TB drive from 500 GB and it is nearly full.

**Comment by SimonCapewell** [comment]
How old would non nextgen hardware be? The code's at least 5 years old, probably even more. My guess would be that older hardware would be catered for by this PR even if the 800ms delay code was removed, but a guess is all it is.

Movielist: I've also got a 2TB drive, it's got about 1.5TB of recordings organised in folders. Opening and populating the trash can (which has the most recordings of any directory on my box - 87), takes around 400ms. The root, which has 9 subfolders and 9 recordings takes a bit less: 350ms.

**Comment by SimonCapewell** [comment]
Oh yeah, I should also mention that the skin selector screen takes a good 5 or 6 seconds to populate here on first load.

**Comment by Huevos** [comment]
I updated next gen recently so it includes all ARM boxes. But anyway sooner or later we are going to cull some of this older hardware.

On movie selection code I get a long spinner before there is any sign of it loading, maybe because the HDD is spun down.

**Comment by Huevos** [comment]
Simon what hardware are you testing on?

**Comment by SimonCapewell** [comment]
I've got an XTrend ET8500 which is about a year old, with 3 DVB-T2 tuners and a 2TB internal 2.5" HDD.

I don't get a spinner loading the movielist, probably because I run with timeshift permanently on. I do get a big delay coming out of standby as the HDD spins up though.

**Comment by IanSav** [comment]
I would like to applaud any attempt to make the UI behave or at least feel more responsive.

I use a much older and slower Beyonwiz T3.  It is based on the old INI hardware.  If you would like some timing reports on this hardware then please tell me how the measurements should be taken.

**Comment by RobvanderDoes** [comment]
I did some tests on my most commonly used hardware.
Tested on dev-5.2.028.004 (without any modification) or on release 5.2.027 when no dev-build available.
Source of EPG is EIT (for Dutch and German services) and Freesat (for UK services).
Size of epg.dat is around 13MB
Graphical EPG is set to PiG, 8 services, 300 minutes timescale
'lab1' is present in active skin.
Tested on VU+ DUO2, VU+Ultimo, Xtrend ET8000, MB Premium Ultra, GB Quad Plus, VU+Solo2, VU+ Ultimo4k (so virtually all generations of hardware)

Results:
1- Graphical EPG opens virtually instantaneous, so quick that the 'Wait-message' didn't even show.
2- Opening movie list (or opening another bookmark) first time takes some time (wait message shows), and even after loading recordings that are new since last opening show initially '0 MB' (only when highlighting them a second time shows the real value).
3- Opening skin selector takes quite some time (and has always done so).
4- There is no difference in reaction between the hardware I used. I didn't measure the times, so this is not scientific, but the G-EPG never gave a slacky response (even on the contrary).

**Comment by RobvanderDoes** [comment]
I redid the G-EPG test as above with https://github.com/openvix/enigma2/commit/51631986ca039d9c23e49a710c9641ccf4d88dbf embedded.
There was no noticeable change in behaviour; not on any of the three generations hardware.
But as I tried to make clear before: generation 1 (VU+Ultimo) is just as fast in opening my G-EPG as generation 3 (VU+Ultimo4k).

**Comment by Huevos** [comment]
Rob in my test there is a horrible delay when the message is shown. And I am talking about with the current code, not this PR.

**Comment by RobvanderDoes** [comment]
Then it might be worthwhile to find out why the difference between your setup (horrible) and mine (fine).
I gave the details about my setup above, maybe you can provide yours?

**Comment by Huevos** [comment]
Run current Dev branch on sf4008.

**Comment by RobvanderDoes** [comment]
My setup was:

> Tested on dev-5.2.028.004 (without any modification) or on release 5.2.027 when no dev-build available.
> Source of EPG is EIT (for Dutch and German services) and Freesat (for UK services).
> Size of epg.dat is around 13MB
> Graphical EPG is set to PiG, 8 services, 300 minutes timescale
> 'lab1' is present in active skin.

And the second series was 

> I redid the G-EPG test as above with [5163198](https://github.com/OpenViX/enigma2/commit/51631986ca039d9c23e49a710c9641ccf4d88dbf) embedded.

I forgot to say that I used as skin ViX-HD, Magic-FHD & S1080 (no noticeable differences between the skins).

So it might be worthwhile to try and find the differences between your setup and mine.

**Comment by RobvanderDoes** [comment]
I just did a similar test on ATV (ET8000) and PLi (VU+Ultimo) and the result was the same: virtually instantaneous presentation of the G-EPG. The EPG source and settings were the same as in my previously reported tests.

Given the (huge) differences between my test results and those from Huevos (and probably others) it seems worthwhile to spot the culprit differences (in setup).

**Comment by Huevos** [comment]
@SimonCapewell please test the following commit on you ET8500 before we go any further.

https://github.com/Huevos/enigma2/commit/3bf00bbc4a18c09513304072a8ca054207df583a

**Comment by Huevos** [comment]
Rob, what exactly are you testing? Current code or Simon's code?

**Comment by RobvanderDoes** [comment]
A few posts above says exactly what I tested.

**Comment by Huevos** [comment]
Tested on dev-5.2.028.004 (without any modification) or on release 5.2.027 when no dev-build available.

I've got no idea what that contains.

**Comment by RobvanderDoes** [comment]
I take it that's a joke.

**Comment by SimonCapewell** [comment]
The new about code shows broadcom 7241, 1GHz dual core. The headline clock speed should be 1.3GHz. 
Codewise, I've pruned out any artificial 800ms waits by removing the non nextgen code as well, just to be sure. The delay loading the screen is there regardless of skin. I'm running at 10 rows, 240 minutes wide, 5MB of EPG.dat

I've been attempting to flash a clean image onto the second bootloaded, but the box isn't playing ball. Flashing seems successful, but no multiboot menu appears. Grr.

**Comment by RobvanderDoes** [comment]
What is the source of your EPG data?

**Comment by Huevos** [comment]
Simon that doesn't make sense. I haven't changed anything in the code that reads the speed. Need to get some debug for that.

**Comment by SimonCapewell** [comment]
Yeah, tell me about it. Can't flash the box via USB (using the same stick as last time), slow EPG, wrong clock speed being reporting. It makes me wonder if I've got slightly duff hardware!

@RobvanderDoes 
I'm using the broadcast Freeview EPG.

@IanSav `lab1` has been in the EPG code for a while. If there's a place where skin properties are documented I can make sure it's mentioned.

Test wise, I ran e2 in a console session, and used the timestamps on debug output from the keyup event on the Guide button until a `print` statement placed at the end of EPGSelection's `hidewaitingtext` which in this PR is renamed to `loadEPGData`

**Comment by AbuBaniaz** [comment]
Huevos' latest commit shows correct speed for me. Previous one showed wrong speed

Can you not flash using Image Manager?  You can also flash by command line if you want using grog68's script.
```
wget --no-check-certificate -O install_vix.sh https://www.dropbox.com/s/hc2cdr116lvx3dj/install_vix.sh?dl=1 && bash install_vix.sh
```

**Comment by SimonCapewell** [comment]
Think I just need to get a new memory stick. Any recommendations what tends to work best?

**Comment by Huevos** [comment]
Depends what it is for. Flashing or storage.

**Comment by SimonCapewell** [comment]
Flashing. I've a 512MB stick that isn't recognised by the firmware.

**Comment by RobvanderDoes** [comment]
Try using the attached exe for formatting the drive; that usually works.
[HPUSBFW_v2.2.3.zip](https://github.com/OpenViX/enigma2/files/2904860/HPUSBFW_v2.2.3.zip)

**Comment by Huevos** [comment]
Needs to be FAT32 format for flashing.

**Comment by RobvanderDoes** [comment]
This PR is now open for 17 days; what do we do with it?

**Comment by SimonCapewell** [comment]
Feel free to cherry pick the skin selector change if you're not happy with the EPG bit

**Comment by Huevos** [comment]
Leave it open. Do not merge.

**Comment by Huevos** [comment]
There is a thread running on the forum.

**Comment by Huevos** [comment]
Problem is it should have been individual PRs.

**Comment by Huevos** [comment]
Also, @SimonCapewell have you tested the load time of the epg now et13000 is in Next gen?

**Comment by SimonCapewell** [comment]
We can still make it individual PRs if you prefer.

I'll test again against the latest nextgen definition later

**Comment by RobvanderDoes** [comment]
> Feel free to cherry pick the skin selector change 

Done that: https://github.com/openvix/enigma2/commit/5bfd361458652a196e0dbf94c500fb86a3ff04ec

**Comment by RobvanderDoes** [comment]
Since I've cherry picked the skinselector (that gives a huge improvement in UI-responsiveness) I suggest to close this PR and create a dedicated one for the EPG-part, once your testing is done and successful.

**Comment by AbuBaniaz** [comment]
That is not cherry picking. It is manually adding code.

People have had to spend considerable time unraveling manual code additions that prevent further merges.

I believe some people call "cherry picking" "drag and dropping".

**Comment by RobvanderDoes** [comment]
Nope.
I picked the complete PY from the PR and referred to it.

**Comment by Huevos** [comment]
Rob what hardware did you test that on? If it was not Next gen the commit needs reverting. The whole point was for Simon to test the current code before this commit was accepted.  I said above don't pull and that we were having a discussion on the forum. Also please do not do commits like that. Cherry pick properly.

**Comment by Huevos** [comment]
> 
> 
> Nope.
> I picked the complete PY from the PR and referred to it.

That is not how to cherry pick. Use git functions.

**Comment by RobvanderDoes** [comment]
Tested on DUO2, Ult4k, GB Quad+, ET8000, Ult

**Comment by Huevos** [comment]
So what was the test? Because for me the current code is instantaneous without this commit.

**Comment by RobvanderDoes** [comment]
It has never been instantaneous for me, not on any box, for years. Now it is.

**Comment by RobvanderDoes** [comment]
Be aware that opening the skin-selector within a certain amount of time from a previous opening is also fast on current code. It's after a reboot and when a long time has passed since the previous opening that opening takes a long time.
Years ago Andy already tried to speed this up, but he never succeeded; now it has been fixed.

**Comment by SimonCapewell** [comment]
Probably something to do with filesystem caching. I've noticed that resolveFilename can be a bit costly.

**Comment by Huevos** [comment]
Simon, try the current epg code on your ¿ET8500? see if you are happy now nextgen is updated.

**Comment by SimonCapewell** [comment]
I've tested with the current Dev branch of EPGSelection.py and HardwareInfo.py, I don't see any difference in load time of the EPG - there's still the 0.5s delay between pressing the button and the EPG appearing.

**Comment by Huevos** [comment]
SImon, sorry to be a pain but can we have this as 2 pull requests.

Problem is I want both commits to show in the history individually, but this pull request also contains all those merge commits. Squash and merge would hide them but that means only 1 commit would show.

**Comment by AbuBaniaz** [comment]
Added here
https://github.com/OpenViX/enigma2/commit/7a1b46949e86828ed35291b6c221965cedd45c92

**Pull request closed without merging**
