### PR TITLE
Remove superfluous usage of skin_default in image paths, don't hardco…

### PR DESCRIPTION
**Pull request by persianpros**
…de these kind of things.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Thank you

**Comment by persianpros** [comment]
Your welcome :)
I sent two more for vix to help you with recent changes:
https://github.com/OpenViX/vix-core/pull/70
https://github.com/OpenViX/HRTunerProxy/pull/39

**Comment by IanSav** [comment]
Thank you for your support and assistance in the clean up process.  :D

**Comment by persianpros** [comment]
Your welcome :)
Is this needed for openatv as well?

**Comment by IanSav** [comment]
OpenATV, OpenPLi and OpenViX now run the same code so if you have the time and opportunity it would be worth checking OpenATV as well.  You never know what you may find.  :)

**Comment by persianpros** [comment]
Also Open Vision which is us ;)

**Comment by IanSav** [comment]
My apologies for my lack of knowledge / understanding.  What is the preferred upstream image used by Open Vision?

**Comment by AbuBaniaz** [comment]
OpenPLi

**Comment by persianpros** [comment]
@AbuBaniaz 

Two more:
https://github.com/oe-alliance/e2plugins/pull/1
https://github.com/oe-alliance/e2openplugin-CrossEPG/pull/15

Regards,
Persian Prince

**Pull request merged**
