### PR TITLE
Graph epg selection bugfix

### PR DESCRIPTION
**Pull request by SimonCapewell**
Fixes a weird double selection rect glitch when opening the grid EPG if you have any setting other than servicename

Also adds an option to show servicenumber+picon. I'm not keen on the looks of picon then servicenumber: it looks a bit clunky. The channel list does it better, i.e. number, picon, name. Any thoughts on swapping this around in the EPG?

### CODE REVIEW

**Comment by Huevos** [comment]
Please describe the bug that this is to fix.

**Comment by SimonCapewell** [comment]
Sure, you should be able to see this yourself by following these steps, it's not skin dependent
1. Set your graph or text EPG to picon only or anything other than just "service name"
2. Open the graph or text EPG. The code without bugfix does 2 calculations of selection rectangle
    1st is during fillGraphEPG before *setShowServiceMode* has been called, which means it uses the default setting of *servicename*
    2nd time is during *setShowServiceMode*, which recalculates everything again. 

3. When you move the selection down a row, the correct selection rect gets removed, but the incorrect rect remains highlighted:
nd

4. Wait 10 seconds or so and the autorefresh clears the erroneous selection artifact

**Comment by SimonCapewell** [comment]
> May break infobar graph epg.
> As it now ignores the title preferance config.epgselection.infobar_servicetitle_mode.value

Yes, quite right. Overeager code simplification. I've rectified this.

>Also it will not update the list on a change

Yes, however, unless I'm missing something, *EPGSelection.onCreate* is the only caller and it's immediately doing an update in *fillGraphEPG*. If it's a point of principal to have the update just in case another caller is going to use the component, I'd be inclined to introduce a parameter to say not to update while the component is being initialised before first render.

**Comment by RobvanderDoes** [comment]
I confirm bug and fix.

**Comment by RobvanderDoes** [comment]
I confirm this (cosmetic) bug, and fix works without side effects noticed.

**Pull request merged**
