### PR TITLE
Epg selection glitch

### PR DESCRIPTION
**Pull request by SimonCapewell**
This change adds a selection clip region reset when paging up or down. This fixes a glitch in the EPGList when paging. The steps to reproduce are:
2. Open graph EPG
2. Page down using 8
3. Move up or down one row without making the EPG page. You should get a glitch similar to this
grab. Here I've just moved the selection onto the second row of the second page.

You can also repro going up a page.
You only tend to see the glitch if you're landing on a wider cell after the page. Service name settings make no difference

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
There is no way I can reproduce this glitch, so I'll leave committing to somebody who can.

**Comment by AbuBaniaz** [comment]
I could reproduce it.

**Comment by Huevos** [comment]
Happens for me reliably.

**Comment by IanSav** [comment]
I can also reproduce the issue using the steps provided.

**Pull request merged**
