### PR TITLE
 [unicable] add Televes dCSS LNB and MATRIX 

### PR DESCRIPTION
**Pull request by zukon**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Can you please resend to Dev branch?

**Comment by RobvanderDoes** [comment]
No need to bother contributers with wrong branches; you can drag & drop a commit to another branch.

**Comment by AbuBaniaz** [comment]
Please teach me how to drag one commit from one branch into another.

I know how to cherry pick a commit. This would have worked.

**Comment by RobvanderDoes** [comment]
Drag & drop functionality depends on the programm. In SmartGit you can drag & drop a commit and a PR to a branch.
Cherrypicking would indeed also have worked in this case.

**Pull request merged**
