### PR TITLE
Enable a temporary sort override for the current directory when Vix is

### PR DESCRIPTION
**Pull request by original-birdman**
in "global sort method" mode.  Without this the blue "Sort by" options
do nothing - not even say they will do nothing.

Removed some old, irrelevant, GML* comments.

### CODE REVIEW

**Comment by SimonCapewell** [comment]
I've been caught out by this when I had "individual settings for each directory" set to no. I thought sorting using the blue button was broken! The behaviour I was expecting at the time was for the sort to be remembered, i.e. blue being a shortcut to setting the global sort method.

**Comment by original-birdman** [comment]
I reckon it's more useful to do a one-off sort with a different method.  I normally look for things by name, but can also envisage wanting to find a film which is less then 2 hours long.

This change does put up text to remind you which is happening.

The global sort method, and whether it is on, are in the Settings.

**Comment by Huevos** [comment]
Birdman please can you post a method to replicate the bug you are fixing.

**Comment by original-birdman** [comment]
You can replicate it from the info in the commit comment.

Disable the "sort method per-directory" option (so that you have the same sort method for all locations) then open up a movie directory and press the blue "Sort by". Regardless of what you then sleect, nothing happens.

See:
https://www.world-of-satellite.com/showthread.php?59298-Sort-order-in-recording-list-not-working


However I need to re-submit this, as I forgot to put the _(..) i18n bits around the text messages.

**Comment by Huevos** [comment]
OK so we close this one then until you are ready.

**Comment by original-birdman** [comment]
Re-done as https://github.com/OpenViX/enigma2/pull/315

**Pull request closed without merging**
