### PR TITLE
Fecpp

### PR DESCRIPTION
**Pull request by EMJB**
Thanks to a lot of help from birdman, I have been investigating the difficulties found by adm when using the ABM Frequency Finder, and have identified two separate problems as follows:
(1) When using the new DVB API for terrestrial signals, "signalQuality" is calculated by frontend.cpp in calculateSignalPercentage by comparing the "signalQualitydB" with 19 dB, such that 100% is reported for higher levels. However the "signalQualitydB" needs to be about 20 dB to achieve lock, so if lock is achieved signalQuality will almost certainly be 100% for all tuners correctly reporting signalQualitydB. The numbers for cable and satellite will be slightly different, but show similar effects. My suggested changes are included in the attached file.
(2) The Si2169 tuner driver in Xtrend's dvb.ko file reports the "FE_SCALE_DECIBEL" figure as "FE_SCALE_RELATIVE", leading to the use of the legacy API where frontend.cpp lacks any special code to correctly calculate either "signalQuality" or "signalQualitydB" for this tuner. I have included in my frontend.cpp changes to detect & correct this error when it occurs, but should not be activated should the driver ever be fixed.
A major factor in (1) was the apparent assumption by the author that the threshold for achieving lock is an Carrier-to-Noise Ratio of 0 dB rather than ~20 dB. Similar assumption for SNR seem to be made in the legacy API calculations, so I would not be surprised if these also showed signalQuality values of 100% for quite modest signals.
I have taken the opportunity to provide more information on signal content and scaling in the code comments, as these do not seem to be documented elsewhere.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
This is not done right. You have so many commits that are irrelevant. Please start over.

**Comment by Huevos** [comment]
Yes, Abu is right. You need to start on a fresh branch working forward from the current git state.

**Comment by EMJB** [comment]
@ Huevos - I thought that is what I did when I followed the procedure recently by Abu Baniaz. Unfortunately I may not have time to try again for a few days as I suspect part of my problems has been that I am rarely able to spend long enough at one time to work right through the procedure in one session.

**Comment by EMJB** [comment]
@Huevos: Unfortunately while phrases such as "make a new branch" or "send your patch into the new branch" may seem clear and unambiguous to you, I fear that it is my lack of understanding that has caused the problems to date. As a simple example many of the github pages such as https://github.com/OpenViX/enigma2 have a "New Pull Request", and it seems critical that you use the right one, but only after the right sequence of preparatory actions.

Do I take it from your last sentence that Abu is already testing the change in the file defined in my first post, in which case there presumably no hurry to generate a pull request?

EMJB

**Comment by SimonCapewell** [comment]
Apologies in advance if this is teaching you to suck eggs!

The main thing is to always create your new branches off your fork's dev branch. I tend to do this locally and then push changes up to my E2 fork on github before doing the pull request. Assuming you have the git command line installed - you can also do it using Github Desktop or in IDEs like Visual Studio Code if you prefer a UI.

Start by making sure everything in your fork's dev branch is up to date with the Enigma2 repo.
```
git checkout dev
git fetch upstream
```
This will give you some output if there have been any commits in E2 that your fork doesn't have yet
Next you can merge these into your dev branch
```
git merge upstream/dev
```
Now you're ready to create your feature branch using the Dev branch as the starting point
```
git branch my-useful-update
git checkout my-useful-update
```
Now make your changes. In your case where your fecpp branch was based on the E2 master branch, I'd just copy in the specific files that you've made changes to and then review what's different. I like to use Visual Studio Code to do this as it's got a Git tab that shows which files have changed and a file comparison view showing the changes within each file - this makes it easy to undo anything that's not meant to be different!

Once you're happy with your changes, commit them to your local branch. Not sure of the command, I always use VSCode for that!
Then push those changes up to your Github E2 fork
Once you've done this, go to https://github.com/EMJB/enigma2
In the branch dropdown, pick your feature branch
Click *New Pull Request*
The left 2 drop downs are where you want your branch to be merged into. The right 2 drop downs are where you're merging from.
Pick *OpenVix/enigma2* *Dev* <= *EMJB/enigma2* *my-useful-update*

It'd be great if there was a guide to best practises that'd take some of the guesswork out of getting started contributing to E2. I still can't work out what the build/debug/test process is for the c++ side building!

**Pull request closed without merging**
