### PR TITLE
Set self.MountPath in calculateFilename if it is not set.

### PR DESCRIPTION
**Pull request by original-birdman**

### CODE REVIEW

**Comment by original-birdman** [comment]
Vix has added a `freespace()` call, which sets self.MountPath, which `calculateFilename()` then uses. However, external plugins (such as the Series Plugin in `enigma2-plugins`) won't make the `freespace()`call as it is not in all distros.
There is no point in calling `freespace()` itself as the caller won't be able to handle anything it does anyway.

**Comment by Huevos** [comment]
Can the plugin not be made to work in all distros, rather than hijacking our enigma?

**Comment by original-birdman** [comment]
It's Vix which has introduced the new call, so it has to be Vix that handles it.

**Comment by original-birdman** [comment]
Skipping what?
If we skip the `freespace()` call we end up failing recordings set to record on a non-existent file-system when we do have space in the default location (this is what `freespace()` does).

**Pull request merged**
