### PR TITLE
Update EpgList.py

### PR DESCRIPTION
**Pull request by attewell**

### CODE REVIEW

**Comment by Huevos** [comment]
Please explain why you think this commit is necessary.

Also if you are going to send pull requests please include a descriptive commit title, with the reason for your changes.

**Comment by attewell** [comment]
Hi. I was thinking loading of epg data before it draws the epg framework.




dean




Get Outlook for Android







On Wed, Mar 28, 2018 at 6:37 AM +1300, "Huevos" <notifications@github.com> wrote:












Please explain why you think this commit is necessary.


Also if you are going to send pull requests please include a descriptive commit title, with the reason for your changes.

**Comment by Huevos** [comment]
The change is purely cosmetic. It doesn't change anything in how the code runs.

**Comment by SimonCapewell** [comment]
If anything, I'd suggest that getting something drawn on screen to indicate response to a button press as quickly as possible is more desirable. The current EPG is a little sluggish to draw in response on my XTrend 8500. I've been meaning to have a look at why that might be but not had time to delve into the code.

**Comment by attewell** [comment]
it is not a material change.. shouldn't cause any issues




If this change shows an improvement in epg data shown as it's drawn.


And there is a delay between button press and reaction on screen..




I can look at how epg data is read.




How do you debug this. Do you deploy this development code to your own boxes to test




Get Outlook for Android







From: Simon Capewell


Sent: Wednesday, 28 March, 10:25 AM


Subject: Re: [OpenViX/enigma2] Update EpgList.py (#246)


To: OpenViX/enigma2


Cc: attewell, Author






If anything, I'd suggest that getting something drawn on screen to indicate response to a button press as quickly as possible is more desirable. The current EPG is a little sluggish to draw in response on my XTrend 8500. I've been meaning to have a look at why that might be but not had time to delve into the code.

**Comment by RobvanderDoes** [comment]
How long do you keep the button pressed? I ask because the system reacts on button-release, not on button-press.

**Comment by attewell** [comment]
just a short press




Get Outlook for Android







On Wed, Mar 28, 2018 at 4:29 PM +1300, "Rob van der Does" <notifications@github.com> wrote:












How long do you keep the button pressed? I ask because the system reacts on button-release, not on button-press.

**Comment by Huevos** [comment]
Closed, as the suggested change is purely cosmetic.

**Pull request closed without merging**
