### PR TITLE
Add support for KA-SAT (9°E) LNBs

### PR DESCRIPTION
**Pull request by wmoldwin**
This adds LOF settings for the official KA-SAT LNB ([Inverto IDLW-TWNLRA20-D212O-OPP](http://www.inverto.tv/products/product.php?section=1&id=241&cat=92)) used by the Irish Saorsat service.

### CODE REVIEW

**Comment by Huevos** [comment]
Is there a standard Saorsat LOF?

Also the LOF in the commit does not correspond to the LNB you have linked to.

I'm hesitant to accept this commit as this only relates to one transponder across the entire arc, and there are many different Ka LOFs used on other transponders.

**Comment by wmoldwin** [comment]
You're right, I linked to the wrong LNB. Sorry about that. I've fixed the link. 21200 is the correct LOF.

It's not so much Saorsat standard as KA-SAT standard. The LNB is designed to the specifications of the satellite, covering its frequency range of 19700 to 20200 even though all of Saorsat is on only one frequency/transponder. The LNB is meant to be compatible with any other video services that might be carried on KA-SAT in the future, although Saorsat is the only such (public) service there at the moment.

This addition is meant to complement my PR to add a Saorsat bouquet to AutoBouquetsMaker (https://github.com/oe-alliance/AutoBouquetsMaker/pull/39).

**Comment by Huevos** [comment]
Ok, I'll merge these PR's, but could I have a debug log of ABM scan with "Extra debug" enabled.

**Comment by wmoldwin** [comment]
[Enigma2_debug_2017-06-01_19-15-57.log.txt](https://github.com/OpenViX/enigma2/files/1045696/Enigma2_debug_2017-06-01_19-15-57.log.txt)

**Comment by Huevos** [comment]
Sorry, Please commit the PR to the Dev branch.

**Pull request merged**
