### PR TITLE
Greek translation full update 18/7/2016

### PR DESCRIPTION
**Pull request by MCelliotG**
Full Greek translation update for OpenVix

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
@MCelliotG I have reverted the commit. You cannot see that thread in the Developer section of OpenVix forum. You should submit to the Dev branch.

**Comment by MCelliotG** [comment]
I'm sorry, I make translations for various images and plugins directly from github, so I was not aware of that rule! Could you please direct me how I can submit to the dev branch? Or elsehow, could I send the po file somewhere so it can be merged? It's a big effort for a full translation and it would be a pity to be lost.

**Comment by AbuBaniaz** [comment]
No need to be sorry.  Thanks for the good work.

Just fork the Dev branch of image and submit changes that way. If you are using Sourcetree, click on remotes, then click on origin, double click the Dev branch and checkout. You can then make amendments on that branch and submit changes.

github checkout dev

**Comment by MCelliotG** [comment]
Thank you so much! I uploaded the file on the translations section of the ViX forum? Is that OK as well?

**Comment by RobvanderDoes** [comment]
> I uploaded the file on the translations section of the ViX forum! Is that OK as well?
That's even perfect!
My comment wasn't meant to you: you did a good job. But the request should not have been merged, but pulled into the dev-branch. Nothing to do with you, but uploading to the forum is even more easy for us.

**Comment by MCelliotG** [comment]
OK, I'm very glad for this solution! Keep up the good work guys and thank you!!!

**Pull request merged**
