### PR TITLE
Add PEP8.sh tool

### PR DESCRIPTION
**Pull request by persianpros**
@Huevos 

Open Vision uses this tool on Travis with https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/build.sh and https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/.travis.yml (automated)

jbleyel added this to github itself for Open WebIF: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/master/CI

It's safe to use it automatically (we and Open WebIF use it for months) but it's up to you how to use it. PLi won't accept the automation.

Normally you need to run this file manually if you don't want to automate it.

### CODE REVIEW

**Comment by Huevos** [comment]
Could you please give instructions how to run this manually.

**Comment by persianpros** [comment]
In Ubuntu just cd to the dir and run ./PEP8.sh

**Comment by Huevos** [comment]
So, if running manual what happens about $TRAVIS_BUILD_NUMBER?

**Comment by persianpros** [comment]
Nothing and that shows it was a manuall run as it will be wth your name not the bot.

**Comment by persianpros** [comment]
@Huevos 

I just added some new tools to our repos: https://github.com/OpenVisionE2/enigma2-openvision/commit/ebdf7bbcea951f940671b2499cf984fdda0c9bd6

dos2unix fixes files that came from windows time to time by contributors.

chmod fixes permission changes by contributors and in some .bb recipes we use cp instead of install command with 0644 or 0755 so it's needed.

futurize fixes lots of old python codes to be compatible with both py2 and py3 not just py3, it makes so many sources ready for new versions so no other branch will be needed for them also it makes codes similar to each other just like PEP8 so diffs, compares, cherry-picks and merges would be easier across branches and other repos.

**Comment by TwolDE2** [comment]
Pleased to see that you are now using github actions - been using it for some time, very easy to implement

**Comment by persianpros** [comment]
@TwolDE2 

Yep it's very faster too ;)

https://github.com/OpenViX/vix-core/pull/121 is the first PR regarding the new tools and I hope you like the results after the merge.

**Pull request merged**
