### PR TITLE
Fix Picon.py and refresh Hotplug plugin

### PR DESCRIPTION
**Pull request by TwolDE2**
1. Picon.py - bad join statement in remove partition - uses wrong paths in removing Picon path
2. Hotplug - Iansav's code fix, cleanup and add audio CD handling(for later)

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
ill cherry pick

**Comment by AbuBaniaz** [comment]
Picon commit added. I can't find Ian's commit on his fork. His last commit on his fork was on 20 Jan

**Comment by TwolDE2** [comment]
Abu - Ian and I have been working together on this and most of it his code but the commit is only my Git at the moment

**Comment by AbuBaniaz** [comment]
K, I'll pick from your branch then

**Comment by TwolDE2** [comment]
@Abuu - none o fthis is a cherry-pick

**Comment by TwolDE2** [comment]
@Abu - also without this hotplug commit there are exposures

**Comment by AbuBaniaz** [comment]
What are you implying? Please be explicit and complete. Is this commit wrong then https://github.com/OpenViX/enigma2/commit/b199cbb3e64e2ac3cb05ead9be3c0224128171e5

If so I will revert and the commits I picked  and re-open the pull request.

We have had the discussion before, pull requests and commits must be specific to the title.

**Comment by ViX-Sicilian** [comment]
Abu leave the commits as is, do not revert anything.

**Comment by ViX-Sicilian** [comment]
Abu, I've re-opened the PR, please leave it. I'll merge it once the checks are complete.

**Comment by AbuBaniaz** [comment]
OK. But I have picked the changes in already.

**Comment by ViX-Sicilian** [comment]
> 
> 
> OK. But I have picked the changes in already.

Picked in from where?

**Comment by AbuBaniaz** [comment]
I picked them from: https://github.com/TwolDE2/VIX/tree/newfix

**Comment by ViX-Sicilian** [comment]
> 
> 
> I picked them from: https://github.com/TwolDE2/VIX/tree/newfix

Please refrain from picking stuff from Twol's GIT or Huevos GIT, it will be merged once ready.

**Comment by AbuBaniaz** [comment]
It was the branch from which he bundled the commits into one pull request. I have never pulled in anything from Huevos' tree.

However, noted.

**Pull request merged**
