### PR TITLE
Check for fields being False in getInfoCB() rather than just assume t…

### PR DESCRIPTION
**Pull request by original-birdman**
…hat they are strings.

Also re-order some settings and checks.

### CODE REVIEW

**Comment by Huevos** [comment]
Currently being tested by Ralf.

**Comment by Huevos** [comment]
Now I can't find the forum thread. Has this been tested yet?

**Comment by AbuBaniaz** [comment]
https://www.world-of-satellite.com/showthread.php?61097-menu-information-network-crash-after-a-few-seconds

**Comment by IanSav** [comment]
The link posted is not open to the public.

**Comment by Huevos** [comment]
No, because our bugs section is not for the public.

**Pull request merged**
