### PR TITLE
Update pot and po files

### PR DESCRIPTION
**Pull request by persianpros**
Another one: https://github.com/OpenViX/vix-core/pull/116

If you need this for python3 branch as well just let me know.

(Same as https://github.com/openatv/enigma2/pull/1913)

### CODE REVIEW

**Comment by persianpros** [comment]
@Huevos 

Should I send this PR for python3 branch as well or is it compatible to cherry-pick?

**Comment by TwolDE2** [comment]
You do know these files are created by the build? Changing here just means the will be overwritten when the build updates"
We still have to commit them manually but the build process builds the po's

**Comment by persianpros** [comment]
@TwolDE2 

I know, updating pot/po files are for translators to have latest (or similar to latest) pot/po files.

**Comment by AbuBaniaz** [comment]
@persianpros 
I always get errors when using the script here: https://github.com/OpenViX/enigma2/blob/Dev/po/updateallpo.sh
Are there any improvements that can be made to it?

**Comment by persianpros** [comment]
@AbuBaniaz 

I'm not using that, I'll share my modified .sh script here when I get back home today :+1:

**Comment by persianpros** [comment]
@AbuBaniaz 

This is what I used for this repo.

[updateallpo-multiOS.zip](https://github.com/OpenViX/enigma2/files/6356018/updateallpo-multiOS.zip)

**Comment by Huevos** [comment]
Is it ok for us to commit this version?

**Comment by persianpros** [comment]
@Huevos 

Sure, this is what I used for sending you the PR, for your py3 branch you need to change branch in it.

I use this modified version in my ubuntu, not sure how it works on Windows.

**Comment by AbuBaniaz** [comment]
Thank you

**Comment by Huevos** [comment]
Thanks

**Comment by AbuBaniaz** [comment]
Are the warnings in the attached of any concern?
[translator script.txt](https://github.com/OpenViX/enigma2/files/6411496/translator.script.txt)

**Comment by Huevos** [comment]
`return _("Your %s %s has no internet access, please check your network settings and make sure you have network cable connected and try again.") % (getMachineBrand(), getMachineName())`

Those warnings just point out it is impossible for the translator change the order of MachineBrand and MachineName in the translation output.

**Comment by Huevos** [comment]
In Py2 you are screwed.
```
>>> stuff_in_string = "Shepherd %s is %d years old." % (shepherd, age)
>>> print(stuff_in_string)
Shepherd Martha is 34 years old.
```

In Py3 you can change the order
```
>>> shepherd = "Martha"
>>> age = 34
>>> # Note f before first quote of string
>>> stuff_in_string = f"Shepherd {shepherd} is {age} years old."
>>> print(stuff_in_string)
Shepherd Martha is 34 years old.
```

Quote from: https://matthew-brett.github.io/teaching/string_formatting.html

**Pull request merged**
