### PR TITLE
Finish correcting DoblyDigital typo

### PR DESCRIPTION
**Pull request by BrianG61UK**
Finish correcting DoblyDigital typo which @Huevos partially fixed in the same commit as he fixed audioSelectionLong

### CODE REVIEW

**Comment by Huevos** [comment]
This does not match the string in the .py file.

`"Dolby Digital downmix is now %s"`

**Comment by BrianG61UK** [comment]
@Huevos So what you're saying is that you made the mistake of not changing the po files (and pot file) because you're lazy rather than because you didn't realize it needed doing?
There is now clearly absolutely no way you could have thought they were already correct because you changed the string yourself!

**Comment by Huevos** [comment]
@BrianG61UK this is a job for the translators. How would I know where "%s" should be inserted into the translated string in 30 languages.

**Comment by BrianG61UK** [comment]
@Huevos pity you didn't point that out earlier when I first mentioned po and pot files on the forum.

**Pull request closed without merging**
