### PR TITLE
Ensure updated sort method is saved in per-directory mode.

### PR DESCRIPTION
**Pull request by original-birdman**
In global sort mode let the user choose whether the change is permanent or temporary.

### CODE REVIEW

**Comment by original-birdman** [comment]
There are still some issues to look at in this area, but this fixes one problem.

(NOTE: the `Components/MovieList.py` changes are only to comments. I suspect that the _lack_ of comments as to what is going on is part of the problem with the code in this area).

**Comment by original-birdman** [comment]
Has this been overlooked, or is it being ignored?

**Comment by IanSav** [comment]
It isn't in a Dev build so I haven't looked at it.  It is difficult for me to integrate ad-hoc code into my build / test environment.

**Comment by original-birdman** [comment]
> It isn't in a Dev build

It's a PR against Dev. My question was about getting it _committed_ there.

> By the way, I don't use per directory settings.

Neither do I, but when a bug is reported for that setting I'll still look at it and (try to) fix it.

**Comment by ViX-Sicilian** [comment]
I'll accept this into next dev build.

**Comment by IanSav** [comment]
The bug was in the global settings and not the per directory settings.  My fix corrected the issue but you wanted to create a new temporary sort type and changed the agenda.

To be able to perform any sort of testing you will need to specify how you expect the sort functions to work now.

**Comment by original-birdman** [comment]
The originally-reported bug was in the per_directory setting.

From 
>In the sortBy() method the newly selected sort mode is not set or saved if the config.movielist.settings_per_directory is True.

but your fix meant that the temporary sorting for a _global_ setting (that had been there for a while) would become a permanent setting'
This fix corrects the original issue while making whether it is a perm/temp sort for global methods user-selectable.

**Comment by IanSav** [comment]
I am still concerned that the differentiation between "Sort" and "Sort By" seems to not have been understood.  This may have affected the bug reporting.

In my limited testing I could not confirm the bug as you listed.  The per directory settings appeared to be working fine.  At Rowland's request I quickly tested all the sort functions and fixed the only bug I found.  I believe that Rowland confirmed my observations and fix.

**Comment by original-birdman** [comment]
> In my limited testing I could not confirm the bug as you listed. The per directory settings appeared to be working fine.

It isn't in the current source. The new value is not being saved.

> I am still concerned that the differentiation between "Sort" and "Sort By" seems to not have been understood. This may have affected the bug reporting.

I'm checking both.

**Comment by RobvanderDoes** [comment]
Findings on dev 5.2.028.002 with this PR embedded:

A-With "Use individual settings for each directory" = True:
A-1- Blue button = "Sort by". It brings up a pull down list in which one can make a choice.
This choice is being saved, also to the menu (the latter is new, and I'm not sure if this is desired).
A- 2- Changed blue button to "Sort": that works as 'cycle through', and the button text label only shortly reflects the new sorting before reverting to "Sort".
The sorting is being saved, also to the menu (the latter is new, and I'm not sure if this is desired).

B-With "Use individual settings for each directory" = False & setting not saved:
B-1- Blue button = "Sort by". It brings up a pull down list in which one can make a choice.
This choice is not being saved, which is correct.
B- 2- Changed blue button to "Sort": that works as 'cycle through', and the button text label shortly shows the current sorting before reverting to "Sort".
The sorting is not being saved, which is correct.

C-With "Use individual settings for each directory" = False & setting saved:
C-1- Blue button = "Sort by". It brings up a pull down list in which one can make a choice.
This choice is being saved, also to the menu (the latter is new, and I'm not sure if this is desired).
C- 2- Changed blue button to "Sort": that works as 'cycle through', and the button text label shortly shows the current sorting before reverting to "Sort".
The sorting is being saved, which is new.


Three remarks:
1- Still 'Sort    8' is the default in the menu. As '8' has no meaning, this should be changed.
2- Sometimes the 'Sort'-label shows '?'. Why is that?
3- An amendment is required, as this PR overwrites https://github.com/openvix/enigma2/commit/03ebf8a9b5b054ea763252e1dfe147a0aa1cf907

**Comment by original-birdman** [comment]
> Three remarks:
1- Still 'Sort 8' is the default in the menu. As '8' has no meaning, this should be changed.

8 _does_ actually have a meaning. It's a GroupWise sort. It's just that this has no text to represent it and there is no way  to actually _select_ it as a sort method. It just happen to be the default.
On the list of things to do once this is in place to fix the reported bug.

> 2- Sometimes the 'Sort'-label shows '?'. Why is that?

One of the sort options is "Shuffle" (random). That's what gets displayed for this mode.

> 3- An amendment is required, as this PR overwrites 03ebf8a

Which is why I wanted to get _this_ fix committed before moving on to tidying up other things.
That other commit is just a one-line deletion. That one line can be deleted from this too.

So, do I need to submit another PR or can the merge be done manually?

**Comment by RobvanderDoes** [comment]
'8' may have a meaning for a coder, but it doesn't for a user. And the menu is meant for the user.
tbh: I wouldn't even know what 'GroupWise sorting' would do....
Why not delete this sorting and choose a 'normal' sorting as default?


IMHO this PR can be amended to prevent the mentioned overwriting of an existing commit; this would be cleaner than to re-add that commit later on.

**Comment by original-birdman** [comment]
> 8' may have a meaning for a coder, but it doesn't for a user. And the menu is meant for the user.
tbh: I wouldn't even know what 'GroupWise sorting' would do....
Why not delete this sorting and choose a 'normal' sorting as default?

As I've said before. It's on the list of things to look at once the reported bug is fixed.

> IMHO this PR can be amended to prevent the mentioned overwriting of an existing commit; this would be cleaner than to re-add that commit later on.

I'll resubmit an amended one later, then.

**Comment by original-birdman** [comment]
Resubmitted as https://github.com/OpenViX/enigma2/pull/380, to alow for the fact that https://github.com/OpenViX/enigma2/commit/03ebf8a9b5b054ea763252e1dfe147a0aa1cf907 got in the way.

**Comment by IanSav** [comment]
> '8' may have a meaning for a coder, but it doesn't for a user. And the menu is meant for the user.
> tbh: I wouldn't even know what 'GroupWise sorting' would do....
> Why not delete this sorting and choose a 'normal' sorting as default?

The default GroupWise setting is an important setting that should NOT be deleted.  I believe that the GroupWise option redefines the sort order depending on the the type of media being viewed.  For Recordings this means to sort by recording time (descending) and then by name (ascending).  I don't remember to sort orders used for Music and Photographs.

**Comment by RobvanderDoes** [comment]
One way or another: a solution has to be found for presenting the user a meaningless '8'.

**Comment by IanSav** [comment]
As I have tried to suggest MANY times, the Beyonwiz version of MovieSelection has all these and many more fixes and enhancements.

I have not tried to implement any more fixes or improvements to this code as my first attempt to help, at the request of Rowland, was simply rejected.  I don't have enough free time to waste on creating and testing fixes to this code to have them rejected.  I will try and merge these changes into my development and test environment so that I can try out the changes.

**Comment by RobvanderDoes** [comment]
As I suggested before it is absolutely pointless to point to another image that does everything much better, as you refuse to create a PR for this and the Beyonwiz doesn't even support the hardware the ViX-team supports so none of us can do any useful comparison.
Please remember that not just one commit of just one file is involved: this is about many commits in many files, which makes cherry picking virtually impossible.

**Comment by RobvanderDoes** [comment]
> I don't have enough free time to waste on creating and testing fixes.....

Please remember I spent a huge amount of time testing your changes (new setup/help/plugin and more), none of which lead to any PR.

**Comment by IanSav** [comment]
> As I suggested before it is absolutely pointless to point to another image that does everything much better, as you refuse to create a PR for this and the Beyonwiz doesn't even support the hardware the ViX-team supports so none of us can do any useful comparison.

The Beyonwiz image is a close derivative of OpenViX.  If you will cast your memory back I raised the Beyonwiz code suggestion to Simon as a potential starting point for all his proposed changes and improvements to MovieSelection.  I never proposed or committed to moving the code myself.

> Please remember that not just one commit of just one file is involved: this is about many commits in many files, which makes cherry picking virtually impossible.

I never suggested cherry picking.  Trying to achieve all the Beyonwiz fixes and enhancements as a very long series of commits is likely to be an arduous and demanding process.

**Comment by IanSav** [comment]
> > I don't have enough free time to waste on creating and testing fixes.....
> 
> Please remember I spent a huge amount of time testing your changes (new setup/help/plugin and more), none of which lead to any PR.

In this case a pull request was created, merged and then reverted.  In the case of the new Setup code you were testing only you had any issues with the code.  Given that you have an issue I can't proceed to a pull request until everyone, including you, can run the code without issue.

**Comment by IanSav** [comment]
For the benefit of others, Beyonwiz don't use satellite tuners.  We (Australia) are a DVB-T/T2 only market.  The issue Rob had with my new Setup code was in the Satellite settings.  I can't reproduce Rob's environment and hence his crash reports on my equipment.

**Comment by RobvanderDoes** [comment]
And as long as no PR has been created and my testing was only 'in private', no one will test it either. The same applies to the new-help and your plugin.

**Comment by IanSav** [comment]
If the new Setup code failed your testing then there is no point in proceeding to give it to others until it works properly for you.  I don't believe in submitting code that doesn't pass my initial testing or the few people with whom I share the pre-release code.  Enigma2 has enough dodgy code in it without adding to the mess.

Prl still has more changes before he submits the new Help code.  So far it is testing well.

My InfoBarRecTimers plugin will get wider testing when it is complete.  You were given a sneak peek to an early alpha version of the code with a view to getting your input into the plugin design and functions.  Much of what you wanted has now been added to the code.  The plugin has significantly changed since you last took an interest.

**Comment by RobvanderDoes** [comment]
> If the new Setup code failed your testing then there is no point in proceeding to give it to others until it works properly for you.


You missed my point. I reacted on your remark that a PR not being in a dev-build, and hence having to download just one file to do a proper testing was much trouble for you.

Anyway, now that you're on to it: so one failing test by just one tester is your reason to stop development? IMHO it should encourage you to get more testesters involved, especially testers who could do a bit of debugging and coding themself. A proper way for this is to add a PR or a test-setup via the forum, or even much better: create a branch specifically for this feature.
Just stopping means a lot of wasted time and energy.

**Comment by IanSav** [comment]
Is there a point to these posts, they appear quite hostile and non productive!

I find it ridiculous that you comment on the complexity of my production, development and testing environment when you likely have no idea of how my my PVRs (receivers), computers and NAS devices are all interconnected and interoperate.  I have limited resources so try to make the most of them.

The InfoBarRecTimers plugin distraction was triggered to address an issue and requests for the Beyonwiz image.  I decided to make the code more open hence my inviting you to comment on the early development code.

Who said I have stopped development on the new Setup system?  It keeps being delayed by my being pulled into some productive and some non productive fix requests and discussions.  As I previously indicated, I was asked to step in to fix the sort issue with MovieSelection.  I did as I was asked.  Unfortunately: "No good deed goes unpunished!"  :(

There is no point in widespread testing of any new code until the code is complete and has passed my own internal testing.  I will generally not release any code until it is tested and has a reasonable chance of working elsewhere.  If I am happy with the completed code I then send it on for a peer code review.  When that iterative cycle completes I will then submit the code for wider testing and publication to a repository.  To do anything less is just wasting the limited developer resources available for Enigma2.

**Comment by RobvanderDoes** [comment]
> Is there a point to these posts, they appear quite hostile and non productive!

Apparently not, as you simply continue to miss my point.

**Pull request closed without merging**
