### PR TITLE
Update MovieSelection.py

### PR DESCRIPTION
**Pull request by digicasi**
don't stop live preview when exiting movie list.

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
I tested this, but I can't see any difference in behaviour. Please explain what you mean exactly.

**Comment by digicasi** [comment]
hi rob, 
here's the procedure to see the difference:
- enter the movie/recordings list; life tv channels continues to play in the pig frame (if enabled in settings)
- when you exit the movie list life tv gets disrupted (black frame)
- with the fix on exit live tv channel continues without disruption in full size.
this is similar to the epg behavior.
thanks for checking
digicasi aka 2stein

**Comment by digicasi** [comment]
sorry, erroneously close the merge request

**Comment by RobvanderDoes** [comment]
That's what I thought it would do, but it doesn't. Behaviour is identical.
But this may be dependant on hardware/drivers: I tested on GB Quad +.

**Comment by digicasi** [comment]
I'm on VU+ DUO2.

**Comment by digicasi** [comment]
could anyone with a duo2 please test this? works here nicely. :-) thanks.

**Comment by RobvanderDoes** [comment]
As it doesn't work for the Quad as I wrote above, there's not much point in testing on another box. We can't accept changes for a specific box.

**Comment by andyblac** [comment]
the black frame as you call it, is needed so the channel can restart PTS.

**Comment by digicasi** [comment]
ok... but if i just enter the movie list (without starting a movie playback) and then exit again... there is no need to restart pts, right? in this case my if statement may need to be a bit more specific (might need your help here) thanks.

**Comment by andyblac** [comment]
you could something to check for a preview started or a movie played, and if TRUE then only do the service stop.

**Comment by digicasi** [comment]
yes, that's an option. however, i wonder whether the stopService() is really required in abort() because it is already done in playbackStop().

**Comment by digicasi** [comment]
don't think i can do better than that.
works perfectly on vu+ and shouldn't hurt on other boxes.

**Comment by digicasi** [comment]
forget it.

**Pull request closed without merging**
