### PR TITLE
updates

### PR DESCRIPTION
**Pull request by zukon**

### CODE REVIEW

**Comment by Huevos** [comment]
Please explain the delete channel commit. Which button was not working?

**Comment by zukon** [comment]
In CommonInterfaceAssignment plugin - red buton don't delete channel from list, just close window.

**Comment by TwolDE2** [comment]
@zukon - I am assuming that you build your own images? I would like to make changes to this commit but will need testing - can you do that.
Also to save (my) time how far back did you go on the repo for the filepush changes?

**Comment by zukon** [comment]
I have date: 26-9-2020 in my archive. Now I don't have time to search more. 

I can test in the evening.

**Comment by Huevos** [comment]
This commit just rewinds to July 14, 2019 prior to Simon's changes, when eFilePush was completely unstable, like PLi's still is.

**Pull request closed without merging**
