### PR TITLE
Change primetime to left edge

### PR DESCRIPTION
**Pull request by AbuBaniaz**
Change primetime to set the time of the left hand edge of the grid EPG

### CODE REVIEW

**Comment by Huevos** [comment]
The primetime should be shown allowing for the amount of history that the user ASKED to be displayed!

Randomly jumping to some point against the wishes of the user is not a good approach.

**Comment by AbuBaniaz** [comment]
I have already cherry picked this bug fix. Simone had added it to his epg custom button branch. 

Thread here:
https://www.world-of-satellite.com/showthread.php?62860-Wrong-Primetime

I had submitted a pull request so it is in the queue of commits to be added while we await migration to new branch. As other commits have started going in, I added it.

**Comment by Huevos** [comment]
Sorry, not sure what you mean about a queue but this commit can't be used.

**Comment by AbuBaniaz** [comment]
No problem. Feel free to revert the commit and leave bug in place.

**Comment by SimonCapewell** [comment]
Happy for this to be reverted, but I'm out of ideas now regarding the bug report about primetime not behaving as expected.

**Comment by Huevos** [comment]
This is like the multi-bouquets bug. First we need a clear list of steps to reproduce the bug. Without that we don't have a lot of hope except finding by brute force. Could it be something to do with program length?

**Pull request closed without merging**
