### PR TITLE
Mask any Wifi password from showing in the debug log.

### PR DESCRIPTION
**Pull request by original-birdman**
Replaces any "-k paswword" with "-k XXXX".

### CODE REVIEW

**Comment by Huevos** [comment]
So if we hide part of the debug how are we supposed to read it?

**Comment by RobvanderDoes** [comment]
I fail to see any reason to accept this PR. Nobody has access to my logs, unless I decide so myself.
And how could I chech if XXXX coincides with my password?

**Comment by ViX-Sicilian** [comment]
I think the main use for this would be if someone wanted to submit a debug log on the forum their debug key would be removed from the logs.

**Comment by RobvanderDoes** [comment]
Even so: what could I possibly do with the knowledge of a password of "vix-forum-user-xxxx"?

**Comment by ViX-Sicilian** [comment]
> Even so: what could I possibly do with the knowledge of a password of "vix-forum-user-xxxx"?

You never know what passwords some people use. I'd never use anything sensitive, but you never know what some do.

**Comment by RobvanderDoes** [comment]
And how could I check if XXXX coincides with my password?

**Comment by ViX-Sicilian** [comment]
> And how could I check if XXXX coincides with my password?

Why would you want to? If you want to check only the password is being masked, check before and after logs.

**Comment by SimonCapewell** [comment]
Surely you check the password by the fact the box isn't connecting? Storing passwords in logs is a bad idea.

**Comment by RobvanderDoes** [comment]
No, It's the other way around: if the box doesn't connect, I need to find out why that's the case.

**Comment by RobvanderDoes** [comment]
Why would you want to? If you want to check only the password is being masked, check before and after logs.

How could I possibly check if the password is not logged?

**Comment by ccs-ccs** [comment]
.....  Some boxes have never logged the wifi password, some do, does yours?

**Comment by RobvanderDoes** [comment]
So some boxes run a different E2?

**Comment by SimonCapewell** [comment]
I was about to go off and check my logs. Then I remembered it's wired :laughing:

**Comment by ccs-ccs** [comment]
**So some boxes run a different E2?**

No.

Same ViX, same room, same passord, one does, one doesn't.

As a poor old end-user, I was most unimpressed to see my wifi passord now in the public domain.

**Comment by RobvanderDoes** [comment]
Same ViX, same room, same passord, one does, one doesn't.

So one needs to keep the password logged to find out why, as this looks like e bug.

**Comment by ccs-ccs** [comment]
> Same ViX, same room, same password, one does, one doesn't.
> 
> So one needs to keep the password logged to find out why, as this looks like a bug.

I doubt it, more likely because one tuner is built in, the other is usb.

**Comment by original-birdman** [comment]
Whether the password is in the logs depends in which sub-system is running the Wifi.
There's MadWifi and "the rest".
One runs wpa-supplicant (which stuffs the password elsewhere) and the others uses wl-config.sh.

Note that wpa-supplicant set-ups don't show the password in the debug log _anyway_, so the argument about "how will we tell from the debug log what password is being used" has no weight, since for many adaptors you've **never** known in the past anyway.

**Comment by ccs-ccs** [comment]
OpenPLi seem quite keen on removing passwords.......

https://github.com/OpenPLi/enigma2/commit/dedc7d4aafb545000d94b4a0cc8290b6eea8e9b1

**Comment by original-birdman** [comment]
The code to `print "read configured interface:"` and `print "self.ifaces after loading:"` _used_ to be commented out.
It looks as though it was uncommented for testing during a set of code changes and not re-commented.

https://github.com/OpenViX/enigma2/commit/ccd9e63e2044d69f0d03964f5a6fd807f9829cef

**Comment by ccs-ccs** [comment]
Print statements commented out in 2012 ......

77d19dfb303e78f74679dea89c15f03abde20c5d

**Comment by Huevos** [comment]
I really can't see a security issue here, unless some fool uses their credit card number as a WPA2 key.

Also the password is easily accessible to anyone who has access to the box (not from the logs).

**Comment by Huevos** [comment]
And, by the way this is not a password, it is a WiFI access key, for a WiFi network that has a range of about 50 feet.

**Comment by original-birdman** [comment]
```
by the way this is not a password, it is a WiFI access key
```

I'll remember that the next time I go into a pub that displays its Wifi password and refuse to use it, instead demanding they give me the Wifi access key.

**Comment by ccs-ccs** [comment]
> I really can't see a security issue here, unless some fool uses their credit card number as a WPA2 key.
> 
> Also the password is easily accessible to anyone who has access to the box (not from the logs).

So what's the reason for **not** suppressing wifi passwords?

If access to the box is restricted to the owner, then wifi passwords are **not** published in the public domain, unless, of course, they are fool enough to help debugging problems by providing debug logs.

Maybe I should open a thread on the ViX forum and see what the reaction is? How would you like me to word it?

**Comment by Huevos** [comment]
This is in debug logs. The whole point of debug logs is to contain debug info. This PR is making a mountain out of a molehill.

**Comment by ccs-ccs** [comment]
> This is in debug logs. The whole point of debug logs is to contain debug info. This PR is making a mountain out of a molehill.

Since when have people's private passwords been a necessary part of debugs logs?

**Comment by Huevos** [comment]
It is a WiFi key and this is not the olny file that contains it. Please explain how you think this is a security risk.

**Comment by ccs-ccs** [comment]
> It is a WiFi key and this is not the olny file that contains it. Please explain how you think this is a security risk.

It's the only file that gets regularly published on a public forum.

Is there a security risk? I reckon the average punter probably believes there is, and that's all that really matters.

I don't really understand why such a simple PR has been greeted with such derision. I'm amazed, to be honest.

That's me done, clearly you'll reject it.

**Comment by BrianG61UK** [comment]
> 
> 
> It is a WiFi key and this is not the only file that contains it. Please explain how you think this is a security risk.

Okay. I demand you tell me your Wi-Fi "password" NOW or stop saying nonsense like it's not a security risk.

**Comment by RobvanderDoes** [comment]
No problem, here's mine: €7Wk9;%gEP4

**Comment by ccs-ccs** [comment]
> No problem, here's mine: €7Wk9;%gEP4

Maybe you could also include your latitude/longitude or post code, they often get posted as well?

**Comment by RobvanderDoes** [comment]
Is my postcode in the debuglogs then?

**Comment by ccs-ccs** [comment]
> Is my postcode in the debuglogs then?

... "often get posted" is the clue.

**Comment by RobvanderDoes** [comment]
I arrest my case; a paranoid man can (by definition) never be convinced.

**Pull request closed without merging**
