### PR TITLE
Enable remote key translations for receivers with named remotes e.g. GigaBlue

### PR DESCRIPTION
**Pull request by TwolDE2**
Following a question from Abu on providing a Help key on the Giga remote, I tried the usual change in Confugure.ac (which didn't work) and then remembered this old(2015) OpenPli change that was then enhanced by OpenATV and allows a simple process to change  keys.(Its been on my Git since the Giga4K was 1st shipped)
Instructions are in the arn354 commit heading 
Its currently setup to change on the Giga remote, option key -> help key

### CODE REVIEW

**Comment by Huevos** [comment]
Please do not merge this commit. I am closing until discussed.

**Comment by AbuBaniaz** [comment]
Please copy the descussion you are having onto forum so others can see and contribute to too.

**Comment by Huevos** [comment]
What discussion?

**Comment by AbuBaniaz** [comment]
>I am closing until discussed.

**Comment by Huevos** [comment]
If a remote has a missing button there should be an entry in SystemInfo that other code can use.

**Comment by AbuBaniaz** [comment]
Why are you blocking syncing cpp code with PLi?

**Comment by Huevos** [comment]
I am not blocking anything.

**Comment by AbuBaniaz** [comment]
History of the two cpp PLi files
https://github.com/OpenPLi/enigma2/commits/develop/lib/actions/action.cpp
https://github.com/OpenPLi/enigma2/commits/develop/lib/actions/action.h

ViX ones here
https://github.com/OpenViX/enigma2/commits/Dev/lib/actions/action.cpp
https://github.com/OpenViX/enigma2/commits/Dev/lib/actions/action.h

The pull request adds the missing commits and brings cpp code in line with PLi albeit not in the preferred method. Closing the pull request and having a discussion not on forum or public most definitely blocks this. Can we go back to working collaboratively?

**Comment by Huevos** [comment]
I still don't know what discussion you are talking about. As far as I know no discussion was ever started.

**Comment by AbuBaniaz** [comment]
So why did you close the pull request and block syncing cpp code with Pli?

**Comment by Huevos** [comment]
I really can't remember why I closed the request. It was in December. Implying I am actively blocking a fix is ridiculous.

**Comment by AbuBaniaz** [comment]
On Skype, you mentioned that S1080 needed skinning when Help button is pressed. I told you my receiver doesn't have the Help key. Like several other receivers. I asked on Slack. Andy mentioned that the configure.ac needs modifying.

I asked twol if anything could be done. Rest of what happened is above.

You closed the request until it is discussed. And you are now saying no discussion took place. Surely onus is on blocker to air reasons for objections or any other query.

**Comment by Huevos** [comment]
I said S1080 needs skinning for an automatic help key to be displayed when "key_help" is detected. That has nothing to do with this.

I don't remember why I closed the PR. Why can't you accept that. I have no interest in having to justify every action, commit or decision I make. Life is too short. Nor am I blocking anything.

If people pulled their weight I wouldn't be bogged down with all this stuff in the first place.

**Comment by AbuBaniaz** [comment]
Then why not reopen and start discussion?

You don't have to justify commits you make. But closing a pull request requires justification. Otherwise the problem with the pull request will not be resolved and person will keep making same mistake.

The pulling weight you mention was being done in this request. 

Not as if anybody is going to be encouraged to contribute/assist if their efforts are rejected without explanation.

**Comment by Huevos** [comment]
Abu, I am just not sure what you want from me. I told you I don't remember and still you want to persist. I am sure you can decide what to do under your own initiative. No need to involve me. I've got enough on my plate.

**Pull request closed without merging**
