### PR TITLE
[UsageConfig.py] PEP8 clean up

### PR DESCRIPTION
**Pull request by IanSav**
This is my first pull request to this repository so I am taking it slow and easy.  I welcome feedback to help me adjust to the OpenViX style.

I am submitting this cleanup pull request as a precursor to submitting an enhancement pull request to add configurable date and time formats to Enigma2.

### CODE REVIEW

**Comment by rossi2000** [comment]
yo

not sure whats happened here mate,   are you able to submit another pull request with just the changes?

**Comment by IanSav** [comment]
Hi Rossi2000,

I wanted to just raise the pull request for the first commit to test the waters.  The actual change was to be next.  Do you want the PEP8 cleanup *with* the change or are you saying you don't want the cleanup?

(In the Beyonwiz repository we tend to do a PEP8 cleanup first and then make code changes.)

**Comment by rossi2000** [comment]
can you not see all the above commits?   not sure whats happening with your pull request but it wants to merge in 232 other commits

	IanSav  wants to merge 232 commits into OpenViX:Dev from IanSav:UsageConfig-CleanUp

**Comment by IanSav** [comment]
Sorry for the annoyance I think I can see what you mean.

Now to work out how I broke my pull request.  Hopefully this is just a teething issue.  :)  Thanks for your help.

**Comment by rossi2000** [comment]
not a problem dude,  
I would recommend merging latest vix-dev into your repo, and trying it again.

**Pull request closed without merging**
