### PR TITLE
Replace the now-missing buildBouquetID() with a short piece of inline…

### PR DESCRIPTION
**Pull request by original-birdman**
… code.

### CODE REVIEW

**Comment by Huevos** [comment]
Why is buildBouquetID() missing?

**Comment by Huevos** [comment]
Hmm. See it here now.
https://github.com/OpenViX/enigma2/commit/01f676b4151aa5776b0d01a22a787d5f8b65dfd9#diff-cc2409666a500ee7b6bc1051460ae5e0

**Comment by original-birdman** [comment]
> Why is buildBouquetID() missing?

Because a PR was committed hat removed it along with its one other usage.
This just restores the original code, albeit in-line.
It might be that the unicode code could be used here, but it at least seemed importantt to prevent the crash first.

**Comment by Huevos** [comment]
Thanks Gordon. In the end I used the unicode suggestion.

https://github.com/OpenViX/enigma2/commit/e77e622abe612d581ebcdb144b5ea7ed98f67b1b

**Pull request closed without merging**
