### PR TITLE
Remove README entry about site.conf

### PR DESCRIPTION
**Pull request by biot**
There is no site.conf to edit, so it's unclear where you would even create it. However it gets created automatically on the first build, and sets BB_NUMBER_THREADS, BB_NUMBER_THREADS and DL_DIR properly.

### CODE REVIEW

**Comment by TwolDE2** [comment]
This is more of an awareness comment, in that once site.conf is created it requires (for most people) an edit, which is why people who build frequently keep a copy to update any new build environments.
In particular, the location of fetched files needs to be set to a saved location…. This comment at least alerts people to the fact that you need to do something.

**Comment by biot** [comment]
Yes, but I'm saying it automatically gets set to exactly what the entry says: threads/parallel got set to 8 for me, and DL_DIR was set to a "build-environment/sources", which it created. So the entry is superfluous.

**Comment by TwolDE2** [comment]
… but that is not always the best setting, and it really should be changed to save the sources.

**Comment by Huevos** [comment]
It gets created when you init the build folder.

If you find this entry in the readme superfluous just skip it, but it is not being deleted.

**Pull request closed without merging**
