### PR TITLE
[Fixed] possible exception in Pager.py

### PR DESCRIPTION
**Pull request by DimitarCC**

### CODE REVIEW

**Comment by Orlandoxx** [comment]
No more crash, but none menu item works. Selectin Settings, but nothing happens, not asking to enter pin code.

**Comment by DimitarCC** [comment]
It because LCD4Linux do something that new handling doesn't understand....

**Comment by Huevos** [comment]
@Orlandoxx please do not accept pull requests in future.

**Comment by Orlandoxx** [comment]
> @Orlandoxx please do not accept pull requests in future.

Okay. Sorry.

**Pull request merged**
